OT123-300/list-of-activities
alkemyTech/OT123-CLIENT pull request #14
Opened 2022-02-04 05:26 UTC by Raymark12

https://www.loom.com/share/1466d137437f43468403b6c19d7b1ddd

https://alkemy-labs.atlassian.net/browse/OT123-300

2022-02-04 17:07 UTC, dvelezroman requested changes
por que hay otros archivos de otras ramas que no corresponden al criterio que solicita el ticket ?

2022-02-04 20:36 UTC, Raymark12 commented
Tuve que solucionar problemas de eslint viejos porque antes no estaban aplicadas las reglas. Tuve que arreglar eso para comitear.

2022-02-04 20:53 UTC, dvelezroman approved these changes

2022-02-05 05:05 UTC, martinmolina1988 approved these changes

2022-02-05 18:32 UTC, merged