OT123-291 back office user list
alkemyTech/OT123-CLIENT pull request #31
Opened 2022-02-08 22:40 UTC by facundoveliz

https://alkemy-labs.atlassian.net/browse/OT123-291

2022-02-08 22:47 UTC, dvelezroman commented on src/pages/backoffice/users/ListUsers.jsx
> +  *  folder for that
const getUsers = useCallback(() => {
    const res = await getAllUsers()
    setUsersData(res.data.result.user)
}, [getAllUsers, setUsersData])

2022-02-08 22:48 UTC, dvelezroman commented on src/pages/backoffice/users/ListUsers.jsx
> +    const res = await getAllUsers()
`useEffect(() => {
    getUsers()
}, [getUsers])

2022-02-08 22:49 UTC, dvelezroman requested changes
useCallback

2022-02-08 23:27 UTC, patriciodfernandez approved these changes

2022-02-09 02:03 UTC, patriciodfernandez approved these changes

2022-02-09 13:03 UTC, dvelezroman approved these changes

2022-02-09 20:39 UTC, merged