OT123-268/slider
alkemyTech/OT123-CLIENT pull request #5
Opened 2022-02-02 20:17 UTC by Raymark12

##DESCRIPTION
Created a slider using react-responsive-carousel.

https://alkemy-labs.atlassian.net/browse/OT123-268

2022-02-02 20:20 UTC, dvelezroman requested changes

2022-02-02 20:20 UTC, dvelezroman commented on src/pages/home/Slider.js
> +const Slider = () => {
debe poder recibit un array de images ... para que pueda acoplarse a cualquier pagina que lo necesita usar

2022-02-03 01:04 UTC, dvelezroman approved these changes

2022-02-03 19:08 UTC, dvelezroman commented
como se ve ? puedes subir alguna captura de screen o video ?

2022-02-03 19:36 UTC, Raymark12 commented
Ahi agregué un video con loom. @dvelezroman

2022-02-03 21:19 UTC, dvelezroman approved these changes

2022-02-03 22:38 UTC, merged